baseURL = "https://humble-american.netlify.com/"
languageCode = "en-us"
title = "HUMBLE AMERICAN"
theme = "blackburn"

[params]
  subtitle = "I disagree with my opinions"
[taxonomies]
  tag = "tags"
  topic = "topics"
  book = "books"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Books"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "book"
    url = "/books/"
