baseURL = "https://humble-american.netlify.com/"
languageCode = "en-us"
title = "HUMBLE AMERICAN"
theme = "blackburn"

[params]
  subtitle = "I disagree with my opinions"
[taxonomies]
  tag = "tags"
  topic = "topics"
  book = "books"
  wire = "the wire"
  analysis = "analyses"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Analyses"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "analysis"
    url = "/analyses/"
  [[menu.main]]
    name = "Books"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "book"
    url = "/books/"
[[menu.main]]
    name = "The Wire"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "the-wire"
    url = "/the-wire/"
